import Head from "next/head";
import Link from "next/link";
import { getMediumData } from "../util/medium";
import Date from "../components/formattedDate";
import Footer from "../components/footer";

export default function Home({ allPostsData }) {
  return (
    <div className="container">
      <Head>
        <title>Next Medium Export</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <h1 className="title">Posts</h1>
        <div className="posts-container">
          {allPostsData.posts.map((post) => (
            <div className="post-item" key={post.path}>
              <Link href="/posts/[id]" as={`/posts/${post.path}`}>
                <a>
                  <h3>{post.title}</h3>
                </a>
              </Link>
              <Date date={post.pubDate[0]} />
            </div>
          ))}
        </div>
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const allPostsData = await getMediumData();
  return {
    props: {
      allPostsData,
    },
  };
}
